; PlatformIO ESP-IDF Project — ESP-NN Accelerated Inference
[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
board_build.f_cpu = 240000000L

; Flash & Partisi 8MB
board_build.flash_mode = qio
board_build.partitions = partitions_8mb.csv
board_upload.flash_size = 8MB

; PSRAM support
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP_NN=1
