[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; Konfigurasi PSRAM untuk XIAO ESP32S3
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM

; Library TFLite Micro
lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
